name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Позволяет запускать вручную

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Получаем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # 2. Устанавливаем Python для обработки файлов
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # 3. Заменяем плейсхолдеры на реальные секреты
      - name: Replace tokens in HTML files
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          # Создаем Python скрипт для замены
          cat > replace_tokens.py << 'EOF'
          import os
          import re
          
          bot_token = os.environ['TELEGRAM_BOT_TOKEN']
          chat_id = os.environ['TELEGRAM_CHAT_ID']
          
          files_to_process = ['forms.html', 'index.html', 'admin.html']
          
          for filename in files_to_process:
              try:
                  with open(filename, 'r', encoding='utf-8') as file:
                      content = file.read()
                  
                  # Заменяем плейсхолдеры
                  content = content.replace('TELEGRAM_BOT_TOKEN_PLACEHOLDER', bot_token)
                  content = content.replace('TELEGRAM_CHAT_ID_PLACEHOLDER', chat_id)
                  
                  with open(filename, 'w', encoding='utf-8') as file:
                      file.write(content)
                      
                  print(f'✅ Обработан файл: {filename}')
              except FileNotFoundError:
                  print(f'⚠️ Файл не найден: {filename}')
          EOF
          
          # Запускаем скрипт
          python replace_tokens.py
      
      # 4. Деплоим на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
